### ISSUE TITLE
是否采用驼峰命名法

### ISSUE THREAD

**Issue by PelerYuan** [Tommy-Zhang3759/Sysync-WinClient#3]
我发现 `api_workers.py` 中的类命名有点奇怪
比如：
```python
class run_cmd(UDPAPIWorker):
```
要不要改成 `RunCmd` 的形式

**Comment by Tommy-Zhang3759** [comment]
目前项目缺少命名规范文档，是否需要撰写相关文档？

**Comment by PelerYuan** [comment]
我也习惯在Python中用下划线风格，但是根据命名规范，一个类的名字应该用大驼峰表示法，这样可以一眼看出来。
我觉得可以根据 https://peps.python.org/pep-0008/ 的规范来

**Comment by Tommy-Zhang3759** [comment]
已采纳并修复，修复后的分支已并入master
